version: '3'

services:
  gateway_db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - gatewaydb_data:/var/lib/postgresql/data
    networks:
      - backend

  gateway_web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - gateway_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - backend

volumes:
  gatewaydb_data:

networks:
  backend: